mapproject/map/urls.py
from django.urls import path
from . import views
urlpatterns = [
    # path('map/', views.ListFoodView.as_view(), name='list-food'),
    path('map/', views.index, name='first-page'),
    path('map/list/', views.ListFoodView.as_view(), name='list-food'),
    path('map/<int:pk>/detail/', views.DetailFoodView.as_view(), name='detail-food'),
    path('map/create/', views.CreateFoodView.as_view(), name='create-food'),
    path('map/<int:pk>/delete/', views.DeleteFoodView.as_view(), name='delete-food'),
    path('map/<int:pk>/update/', views.UpdateFoodView.as_view(), name='update-food'),
    path('map/meat/', views.meat_view, name='meat-list'),
    path('map/vegetable/', views.vegetable_view, name='vegetable-list'),
    path('map/fruit/', views.fruit_view, name='fruit-list'),
    path('map/drink/', views.drink_view, name='drink-list'),
    path('map/frozen_food/', views.frozen_food_view, name='frozen_food-list'),
    path('map/noodle/', views.noodle_view, name='noodle-list'),
    path('map/seasoning/', views.seasoning_view, name='seasoning-list'),
    path('map/other/', views.other_view, name='other-list'),
    #path('map/update_voice/', views.VoiceUpdateFoodView.as_view(), name='update-food-voice'),
    path('map/process_voice_input/', views.process_voice_input, name='process_voice_input'),
    path('map/process_receipt_input/', views.process_receipt_input, name='process_receipt_input'),
    path('map/register-food/', views.register_food, name='register_food'),
    # path('map/receipt_result/', views.register_food, name='register_food'),
    path('send-notify/',views.my_view),
]

mapproject/mapproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('map.urls')),
]

mapproject/map/models.py
from django.db import models
from datetime import date
from pykakasi import kakasi

# Create your models here.
CATEGORY = (('meat','肉'),('vegetable','野菜'),('fruit','果物'),('drink','飲料'),('frozen_food','冷凍食品'),('noodle','麺'),('seasoning','調味料'),('other','その他'))
UNIT = (('pieces','個'),('grams','g'),('milliliter','ml'))
class Food(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=100, choices = CATEGORY)
    number = models.IntegerField(default = 0)
    unit = models.CharField(max_length=100, choices = UNIT, default='pieces')
    best_by_date = models.DateField(default=date.today)

    def __str__(self): #タイトルを表示
        return self.title

    def change_hiragana(self):
        kks = kakasi()
        change_title = kks.convert(self.title)
        result = ""
        for converted_word in change_title:
            result += f"{converted_word['hira']}"
        return result
    

class Food_template(models.Model):
    title = models.CharField(max_length=100)
    category = models.CharField(max_length=100, choices = CATEGORY)
    day = models.IntegerField(default = 0)

    def __str__(self): #タイトルを表示
        return self.title

mapproject/map/forms.py
from django import forms
from .models import Food


class FoodForm(forms.ModelForm):


    class Meta:
        model = Food
        fields = ['title', 'category', 'number', 'unit', 'best_by_date']
        labels = {
            'title': '食材名',
            'category': 'カテゴリー',
            'number': '個数',
            'unit': '単位',
            'best_by_date': '賞味期限',
        }
    

mapproject/map/views.py
from django.shortcuts import render,get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from .models import Food 
from .models import Food_template
from .forms import FoodForm
from pykakasi import kakasi
from django.contrib import messages

import requests
from django.http import HttpResponseRedirect
from datetime import date, timedelta

import google.generativeai as genai
from PIL import Image, ImageEnhance, ImageFilter
import json
from django.http import HttpResponse


# Create your views here.
#食材表示
class ListFoodView(ListView):
    template_name = 'map/food_list.html'
    model = Food
    ordering = 'best_by_date'

#各食材の詳細表示
class DetailFoodView(DetailView):
    template_name = 'map/food_detail.html'
    model = Food

#食材登録
class CreateFoodView(CreateView):
    template_name = 'map/food_create.html'
    model = Food
    form_class = FoodForm
    success_url = reverse_lazy('list-food')

#食材削除
class DeleteFoodView(DeleteView):
    template_name = 'map/food_delete.html'
    model = Food
    success_url = reverse_lazy('list-food')

#食材修正
class UpdateFoodView(UpdateView):
    template_name = 'map/food_update.html'
    model = Food
    form_class = FoodForm
    success_url = reverse_lazy('list-food')

#肉類表示
def meat_view(request):
    meat_list = Food.objects.filter(category='meat').order_by('best_by_date')
    return render(request, 'map/meat_list.html', {'meat_list': meat_list})

#野菜表示
def vegetable_view(request):
    vegetable_list = Food.objects.filter(category='vegetable').order_by('best_by_date')
    return render(request, 'map/vegetable_list.html', {'vegetable_list': vegetable_list})

#果物表示
def fruit_view(request):
    fruit_list = Food.objects.filter(category='fruit').order_by('best_by_date')
    return render(request, 'map/fruit_list.html', {'fruit_list': fruit_list})

#飲料表示
def drink_view(request):
    drink_list = Food.objects.filter(category='drink').order_by('best_by_date')
    return render(request, 'map/drink_list.html', {'drink_list': drink_list})

#冷凍食品表示
def frozen_food_view(request):
    frozen_food_list = Food.objects.filter(category='frozen_food').order_by('best_by_date')
    return render(request, 'map/frozen_food_list.html', {'frozen_food_list': frozen_food_list})

#麺類表示
def noodle_view(request):
    noodle_list = Food.objects.filter(category='noodle').order_by('best_by_date')
    return render(request, 'map/noodle_list.html', {'noodle_list': noodle_list})

#調味料表示
def seasoning_view(request):
    seasoning_list = Food.objects.filter(category='seasoning').order_by('best_by_date')
    return render(request, 'map/seasoning_list.html', {'seasoning_list': seasoning_list})

#その他食材表示
def other_view(request):
    other_list = Food.objects.filter(category='other').order_by('best_by_date')
    return render(request, 'map/other_list.html', {'other_list': other_list})

#音声修正
def process_voice_input(request):
    kks = kakasi()
    if request.method == 'POST':
        food_name = request.POST.get('food_name')
        counts_str = request.POST.get('counts')
        if not food_name or not counts_str:
            return render(request, 'voice_input_form.html', {'error': '音声入力が取得できませんでした'})
        
        change_food_name = kks.convert(food_name)
        result = ""
        for converted_word in change_food_name:
            result += f"{converted_word['hira']}"
        
        foods = Food.objects.all()
        matching_foods = [food for food in foods if food.change_hiragana() == result]
        
        try:
            counts = int(counts_str)
        except ValueError:
            return render(request, 'voice_input_form.html',{'error': '数が無効です'})

        if counts == 0:
            if matching_foods:
                food = matching_foods[0]
                food.delete()
                return redirect('/map/list/')
            else:
                return render(request, 'food_not_found.html', {'food_name': food_name})  
        elif counts > 0:
            if matching_foods:
                food = matching_foods[0]
                food.number = food.number - counts 
                food.save()
                return redirect('/map/list/')
            else:
                return render(request, 'food_not_found.html', {'food_name': food_name}) 
        else:
            return render(request, 'voice_input_form.html', {'error': '入力が無効です'})
    return render(request, 'voice_input_form.html')

#レシート読み込み (Gemini)
def process_receipt_input(request):
    if request.method == 'POST' and request.FILES['receipt']:
        receipt_image = request.FILES['receipt']
        image = Image.open(receipt_image)
        model = genai.GenerativeModel(model_name = "gemini-1.5-flash")
        prompt = "商品名('name')（ひらがなまたは半角カタカナで書かれているもの）と個数('quantity')（書いていなかったら1個）を商品ごとのJSON形式で表示してください。もし同じ名前の商品があったら、一つにまとめて、個数をその数にしてください。"
        response = model.generate_content([prompt,image])

        parsed_receipt = json.loads((response.text).replace("```json", "").replace("```", "").strip())

        kks = kakasi()
        kks.setMode("J", "H")  # 漢字をひらがなに変換するモード
        conv = kks.getConverter()

        enriched_receipt = []
        for item in parsed_receipt:
            # 商品名をひらがなに変換
            hiragana_name = conv.do(item['name'])

            # ひらがなでテンプレートを検索
            # food_template = Food_template.objects.filter(title=hiragana_name).first()
            # food_template = Food_template.objects.filter(title__icontains=hiragana_name).first()
            food_template = Food_template.objects.filter(title__icontains=hiragana_name).first()

            # 食材テンプレートが見つかった場合、カテゴリーと賞味期限を補完
            #タイトルを一つずつ検証する
            if food_template:
                item['category'] = food_template.category
                item['best_by_date'] = (date.today() + timedelta(days=food_template.day)).isoformat()  # 賞味期限をデフォルトにテンプレートのdayを追加
            else:
                item['category'] = ''
                item['best_by_date'] = (date.today()).isoformat()

            enriched_receipt.append(item)

        form_class = FoodForm

        return render(request, 'receipt_result.html', {'parsed_receipt': parsed_receipt, 'form': form_class})

    return render(request, 'receipt_input_form.html')

#レシート食材登録
def register_food(request):
    if request.method == 'POST':
        # total_items = len(request.POST.getlist('title_1'))  # この例ではアイテム数を取得します
        # total_items = 7
        total_items = sum(1 for key in request.POST if key.startswith('title_'))
        for i in range(1, total_items + 1):
            title = request.POST.get(f'title_{i}')
            category = request.POST.get(f'category_{i}')
            number = request.POST.get(f'number_{i}')
            unit = request.POST.get(f'unit_{i}')
            best_by_date = request.POST.get(f'best_by_date_{i}')
            if title and category and number and unit and best_by_date:
                existing_food = Food.objects.filter(title=title, best_by_date=best_by_date).first()
                # existing_food = Food.objects.filter(title=title).first()
                if existing_food:
                    # 既存データと新規データをまとめる
                    existing_food.number += int(number)
                    existing_food.save()
                else:
                    Food.objects.create(
                        title=title,
                        category=category,
                        number=number,
                        unit=unit,
                        best_by_date=best_by_date
                    )

        return redirect('list-food')  # 成功時のリダイレクト先

    return render(request, 'template_name.html', {'form': FoodForm()})

#賞味期限通知
def send_line_notify(message, token):
   print(f"送信するメッセージ: {message}")
   print(f"使用するトークン: {token}")
   url = "https://notify-api.line.me/api/notify"
   headers = {"Authorization": f"Bearer {token}"}
   data = {"message": message}


   response = requests.post(url, headers=headers, data=data)


   if response.status_code == 200:
       print("通知を送信しました")
   else:
       print(f"通知の送信に失敗しました: {response.status_code}")
       print(f"エラーメッセージ: {response.text}")


def my_view(request):
   # アクセストークンを設定
   token = "xsoprcumx8vI2y0UaTkZBzDlEHMmO39Focb3ciTTKpH"
  
   tomorrow = date.today() + timedelta(days=1)


   # 賞味期限が明日までの食材を取得
   foods = Food.objects.filter(best_by_date=tomorrow)


   # メッセージを作成
   if foods.exists():
       food_titles = ', '.join([food.title for food in foods])
       message = f"注意: 明日が賞味期限: {food_titles} !!!"
   else:
       message = "賞味期限が明日までの食材はありません。"


   # LINEに通知を送信
   send_line_notify(message, token)


   return HttpResponseRedirect('http://127.0.0.1:8000/map/')

#最初の画面
def index(request):
    return render(request, "map/index.html")

mapproject/map/templates/map/drink_list.html
{% extends 'base.html' %}
{% block title %}飲料一覧{% endblock %}
{% block h1 %}飲料一覧{% endblock %}

{% block content %}    
    <div class="category-list">
        <a href="{% url 'meat-list' %}" class="btn button">肉</a>
        <a href="{% url 'vegetable-list' %}" class="btn button">野菜</a>
        <a href="{% url 'fruit-list' %}" class="btn button">果物</a>
        <a href="{% url 'drink-list' %}" class="btn button">飲料</a>
        <a href="{% url 'frozen_food-list' %}" class="btn button">冷凍食品</a>
        <a href="{% url 'noodle-list' %}" class="btn button">麺</a>
        <a href="{% url 'seasoning-list' %}" class="btn button">調味料</a>
        <a href="{% url 'other-list' %}" class="btn button">その他</a>
    </div>
    <p class="task-w"></p>
    <div class="food-blocks">
        {% for item in drink_list %}
        <!-- <div class="p-4 m-4 bg-linen border border-warning rounded"> -->
        <div class="food-block">
            <div class="detail">
                <a href="{% url 'detail-food' item.pk %}">{{ item.title}}</a>
            </div>
            <h5 class="text-dark">{{ item.number }}{{ item.get_unit_display }}</h5>
            <h5>{{ item.best_by_date|date:"Y n/j" }}</h5>
        </div>
        {% endfor %}
    </div>
    <div class="menu-btn" onclick="toggleMenu()">☰</div>
    <div id="side-menu" class="side-menu">
        <ul>
            <p class="task"></p>
            <li><a href="{% url 'meat-list' %}" class="menu-button">肉</a></li>
            <li><a href="{% url 'vegetable-list' %}" class="menu-button">野菜</a></li>
            <li><a href="{% url 'fruit-list' %}" class="menu-button">果物</a></li>
            <li><a href="{% url 'drink-list' %}" class="menu-button">飲料</a></li>
            <li><a href="{% url 'frozen_food-list' %}" class="menu-button">冷凍食品</a></li>
            <li><a href="{% url 'noodle-list' %}" class="menu-button">麺</a></li>
            <li><a href="{% url 'seasoning-list' %}" class="menu-button">調味料</a></li>
            <li><a href="{% url 'other-list' %}" class="menu-button">その他</a></li>
        </ul>
    </div>
{% endblock content %}

mapproject/map/templates/map/food_create.html
{% extends 'base.html' %}

{% block title %}登録{% endblock %}

{% block content %}
    <div class="food-create">
        <p class="task">食材を入力してください</p>
        <form method='POST'>{% csrf_token %}
            {{form.as_p}}
            <input type='submit' value='登録する'>
        </form> 
    </div>
    {% endblock %}

mapproject/map/templates/map/food_delete.html
{% extends 'base.html' %}

{% block title %}削除{% endblock %}

{% block content %}
    <div class="food-delete">
        <p class="task"></p>
        <h2>以下の食材を削除しますか？</h2>
        <p>食材名: {{ object.title }}</p>
        <p>カテゴリー: {{ object.get_category_display }}</p>
        <p>個数: {{ object.number }}</p>
        <p>賞味期限: {{ object.best_by_date|date:"Y n/j" }}</p>

        <form method="post">{% csrf_token %}
            <input type="hidden" name="id" value="{{ object.id }}">
            <!-- <button type="button" onclick="startDictation()">音声入力を開始</button> -->
            <br>
            <button type="submit">{{ object.title }}を削除する</button>
        </form>
    </div>
    <script>
        function startDictation() {
            if (window.hasOwnProperty('webkitSpeechRecognition')) {
                var recognition = new webkitSpeechRecognition();

                recognition.continuous = false;
                recognition.interimResults = false;

                recognition.lang = "ja-JP";  // 日本語に設定
                recognition.start();

                recognition.onresult = function(e) {
                    var result = e.results[0][0].transcript.trim();
                    if (result === "削除") {
                        document.querySelector('form').submit();
                    }
                    recognition.stop();
                };

                recognition.onerror = function(e) {
                    recognition.stop();
                }
            } else {
                alert("お使いのブラウザは音声認識をサポートしていません。");
            }
        }
    </script>
    <!---
    <h1>{{ object.title }}を削除する</h1>
    <form method='post'>
        {% csrf_token %}
        {{ forms.as_p }}
        <button type='submit'>削除</button>
    </form>
-->

{% endblock %}

mapproject/map/templates/map/food_detail.html
{% extends 'base.html' %}

{% block title %}食材詳細{% endblock %}

{% block content %}
    <div class="card">
        <p class="task"></p>
        <h5 class="card-header">{{ object.get_category_display }}</h5>
        <div class="card-body">
            <p class="card-text card-title">{{ object.title }}</p>
            <p class="card-text">{{ object.number }}{{ object.get_unit_display }}</p>
            <p class="card-text">{{ object.best_by_date|date:"Y n/j" }}</p>
            <a href="{% url 'list-food' %}" class="btn button">一覧へ</a>
            <a href="{% url 'update-food' object.pk %}" class="btn button">編集する</a>
            <a href="{% url 'delete-food' object.pk %}" class="btn button">削除する</a>
        </div>
    </div>
{% endblock content %}

mapproject/map/templates/map/food_list.html
{% extends 'base.html' %}
<!-- {% block title %}食材一覧{% endblock %}
{% block h1 %}食材一覧{% endblock %} -->

{% block content %}    
<div class="food1">
    
    

    <div class="category-list">
        <a href="{% url 'meat-list' %}" class="btn button">肉</a>
        <a href="{% url 'vegetable-list' %}" class="btn button">野菜</a>
        <a href="{% url 'fruit-list' %}" class="btn button">果物</a>
        <a href="{% url 'drink-list' %}" class="btn button">飲料</a>
        <a href="{% url 'frozen_food-list' %}" class="btn button">冷凍食品</a>
        <a href="{% url 'noodle-list' %}" class="btn button">麺</a>
        <a href="{% url 'meat-list' %}" class="btn button">調味料</a>
        <a href="{% url 'other-list' %}" class="btn button">その他</a>
    </div>
    <div class="food-blocks-list">
        {% regroup object_list by best_by_date as grouped_by_date %}
        {% for group in grouped_by_date %}
        <div class="best-by-group">
            <h5>{{ group.grouper|date:"Y n/j" }}</h5>
            <div class="group">
                {% for item in group.list %}
                    <div class="food-item">
                        <div class="food-block">
                            <div class="detail">
                                <a href="{% url 'detail-food' item.pk %}">{{ item.title }}</a>
                            </div>
                            <h5 class="text-dark">{{ item.number }}{{ item.get_unit_display }}</h5>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>  
<div class="menu-btn" onclick="toggleMenu()">☰</div>
<div id="side-menu" class="side-menu">
    <ul>
        <p class="task"></p>
        <li><a href="{% url 'meat-list' %}" class="menu-button">肉</a></li>
        <li><a href="{% url 'vegetable-list' %}" class="menu-button">野菜</a></li>
        <li><a href="{% url 'fruit-list' %}" class="menu-button">果物</a></li>
        <li><a href="{% url 'drink-list' %}" class="menu-button">飲料</a></li>
        <li><a href="{% url 'frozen_food-list' %}" class="menu-button">冷凍食品</a></li>
        <li><a href="{% url 'noodle-list' %}" class="menu-button">麺</a></li>
        <li><a href="{% url 'seasoning-list' %}" class="menu-button">調味料</a></li>
        <li><a href="{% url 'other-list' %}" class="menu-button">その他</a></li>
    </ul>
</div>

{% endblock content %}

mapproject/map/templates/map/food_update.html
{% extends 'base.html' %}

{% block title %}修正{% endblock %}

{% block content %}
    <p class="task"></p>
    <div class="food-update">
        <form method='post'>
            {% csrf_token %}
            {{form.as_p}}
            <button type='submit'>修正する</button>
        </form>
    </div>
{% endblock %}

mapproject/map/templates/map/frozen_food_list.html
{% extends 'base.html' %}
<!-- {% block title %}冷凍食品一覧{% endblock %}
{% block h1 %}冷凍食品一覧{% endblock %} -->

{% block content %}

    <div class="category-list">
        <a href="{% url 'meat-list' %}" class="btn button">肉</a>
        <a href="{% url 'vegetable-list' %}" class="btn button">野菜</a>
        <a href="{% url 'fruit-list' %}" class="btn button">果物</a>
        <a href="{% url 'drink-list' %}" class="btn button">飲料</a>
        <a href="{% url 'frozen_food-list' %}" class="btn button">冷凍食品</a>
        <a href="{% url 'noodle-list' %}" class="btn button">麺</a>
        <a href="{% url 'seasoning-list' %}" class="btn button">調味料</a>
        <a href="{% url 'other-list' %}" class="btn button">その他</a>
    </div>
    <p class="task-w"></p>
    <div class="food-blocks">
        {% for item in frozen_food_list %}
        <!-- <div class="p-4 m-4 bg-linen border border-warning rounded"> -->
        <div class="food-block">
            <!--<h5 class="text-dark">{{ item.category }}</h5> -->
            <!-- <h3>{{ item.title }}</h3> -->
            <div class="detail">
                <a href="{% url 'detail-food' item.pk %}">{{ item.title}}</a>
            </div>
            <h5 class="text-dark">{{ item.number }}{{ item.get_unit_display }}</h5>
            <h5>{{ item.best_by_date|date:"Y n/j" }}</h5>
            <!-- <div class="mt-3">
                <a href="{% url 'detail-food' item.pk %}">詳細</a>
            </div> -->
        </div>

        {% endfor %}
    </div>
    <div class="menu-btn" onclick="toggleMenu()">☰</div>
    <div id="side-menu" class="side-menu">
        <ul>
            <p class="task"></p>
            <li><a href="{% url 'meat-list' %}" class="menu-button">肉</a></li>
            <li><a href="{% url 'vegetable-list' %}" class="menu-button">野菜</a></li>
            <li><a href="{% url 'fruit-list' %}" class="menu-button">果物</a></li>
            <li><a href="{% url 'drink-list' %}" class="menu-button">飲料</a></li>
            <li><a href="{% url 'frozen_food-list' %}" class="menu-button">冷凍食品</a></li>
            <li><a href="{% url 'noodle-list' %}" class="menu-button">麺</a></li>
            <li><a href="{% url 'seasoning-list' %}" class="menu-button">調味料</a></li>
            <li><a href="{% url 'other-list' %}" class="menu-button">その他</a></li>
        </ul>
    </div>
{% endblock content %}

mapproject/map/templates/map/fruit_list.html
{% extends 'base.html' %}
<!-- {% block title %}果物一覧{% endblock %}
{% block h1 %}果物一覧{% endblock %} -->

{% block content %}    
    <div class="category-list">
        <a href="{% url 'meat-list' %}" class="btn button">肉</a>
        <a href="{% url 'vegetable-list' %}" class="btn button">野菜</a>
        <a href="{% url 'fruit-list' %}" class="btn button">果物</a>
        <a href="{% url 'drink-list' %}" class="btn button">飲料</a>
        <a href="{% url 'frozen_food-list' %}" class="btn button">冷凍食品</a>
        <a href="{% url 'noodle-list' %}" class="btn button">麺</a>
        <a href="{% url 'seasoning-list' %}" class="btn button">調味料</a>
        <a href="{% url 'other-list' %}" class="btn button">その他</a>
    </div>
    <p class="task-w"></p>
    <div class="food-blocks">
        {% for item in fruit_list %}
        <!-- <div class="p-4 m-4 bg-linen border border-warning rounded"> -->
        <div class="food-block">
            <!-- <h3>{{ item.title }}</h3> -->
            <div class="detail">
                <a href="{% url 'detail-food' item.pk %}">{{ item.title}}</a>
            </div>
            <h5 class="text-dark">{{ item.number }}{{ item.get_unit_display }}</h5>
            <h5>{{ item.best_by_date|date:"Y n/j" }}</h5>
            <!-- <div class="mt-3">
                <a href="{% url 'detail-food' item.pk %}">詳細</a>
            </div> -->
        </div>

        {% endfor %}
    </div>
    <div class="menu-btn" onclick="toggleMenu()">☰</div>
    <div id="side-menu" class="side-menu">
        <ul>
            <p class="task"></p>
            <li><a href="{% url 'meat-list' %}" class="menu-button">肉</a></li>
            <li><a href="{% url 'vegetable-list' %}" class="menu-button">野菜</a></li>
            <li><a href="{% url 'fruit-list' %}" class="menu-button">果物</a></li>
            <li><a href="{% url 'drink-list' %}" class="menu-button">飲料</a></li>
            <li><a href="{% url 'frozen_food-list' %}" class="menu-button">冷凍食品</a></li>
            <li><a href="{% url 'noodle-list' %}" class="menu-button">麺</a></li>
            <li><a href="{% url 'seasoning-list' %}" class="menu-button">調味料</a></li>
            <li><a href="{% url 'other-list' %}" class="menu-button">その他</a></li>
        </ul>
    </div>
{% endblock content %}

mapproject/map/templates/map/meat_list.html
{% extends 'base.html' %}

{% block content %} 
    <div class="category-list">   
        <a href="{% url 'meat-list' %}" class="btn button">肉</a>
        <a href="{% url 'vegetable-list' %}" class="btn button">野菜</a>
        <a href="{% url 'fruit-list' %}" class="btn button">果物</a>
        <a href="{% url 'drink-list' %}" class="btn button">飲料</a>
        <a href="{% url 'frozen_food-list' %}" class="btn button">冷凍食品</a>
        <a href="{% url 'noodle-list' %}" class="btn button">麺</a>
        <a href="{% url 'seasoning-list' %}" class="btn button">調味料</a>
        <a href="{% url 'other-list' %}" class="btn button">その他</a>
    </div>
    <p class="task-w"></p>
    <div class="food-blocks">
        {% for item in meat_list %}
        <!-- <div class="p-4 m-4 bg-linen border border-warning rounded"> -->
        <div class="food-block">
            <!--<h5 class="text-dark">{{ item.category }}</h5> -->
            <!-- <h3>{{ item.title }}</h3> -->
            <div class="detail">
                <a href="{% url 'detail-food' item.pk %}">{{ item.title}}</a>
            </div>
            <h5 class="text-dark">{{ item.number }}{{ item.get_unit_display }}</h5>
            <h5>{{ item.best_by_date|date:"Y n/j" }}</h5>
            <!-- <div class="mt-3">
                <a href="{% url 'detail-food' item.pk %}">詳細</a>
            </div> -->
        </div>

        {% endfor %}
    </div>
    <div class="menu-btn" onclick="toggleMenu()">☰</div>
    <div id="side-menu" class="side-menu">
        <ul>
            <p class="task"></p>
            <li><a href="{% url 'meat-list' %}" class="menu-button">肉</a></li>
            <li><a href="{% url 'vegetable-list' %}" class="menu-button">野菜</a></li>
            <li><a href="{% url 'fruit-list' %}" class="menu-button">果物</a></li>
            <li><a href="{% url 'drink-list' %}" class="menu-button">飲料</a></li>
            <li><a href="{% url 'frozen_food-list' %}" class="menu-button">冷凍食品</a></li>
            <li><a href="{% url 'noodle-list' %}" class="menu-button">麺</a></li>
            <li><a href="{% url 'seasoning-list' %}" class="menu-button">調味料</a></li>
            <li><a href="{% url 'other-list' %}" class="menu-button">その他</a></li>
        </ul>
    </div>
{% endblock content %}